default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: https://github.com/commit-check/commit-check
    rev: v2.1.2
    hooks:
      - id: check-message
        stages: [commit-msg]
      - id: check-branch
      - id: check-author-name
      - id: check-author-email

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: go-format
        name: golang formatters
        language: system
        pass_filenames: false
        entry: go
        args:
          - tool
          - -modfile=golangci-lint.mod
          - golangci-lint
          - fmt
        types: [go]
        stages: [pre-commit, pre-push]
      - id: go-lint
        name: golang linters
        language: system
        pass_filenames: false
        entry: go
        args:
          - tool
          - -modfile=golangci-lint.mod
          - golangci-lint
          - run
        types: [go]
        stages: [pre-commit, pre-push]
